version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002"]
    ports:
      - 4000:4000
      - 5678:5678
    environment:
      - FLASK_APP=node_modules\node-gyp\gyp\pylib\packaging\specifiers.py
