##spring.application.name=batch-api-back
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ecommercedb
#    password: postgres
#    username: postgres
#  jpa:
#    #    properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQL94Dialect
#      ddl-auto: update
#      show-sql: true
#  mvc:
#    path match:
#      matching-strategy: ANT_PATH_MATCHER
#
#stripe:
#  secret-key: sk_test_51NiZKsLtTFoBOb8wTg4V2C3bJqrQ53qMHLusPXct6hp0O3yNtHXfEITKl7bLHNPRG7Egk28A5d1X7H4yoCvUl5kF00OP3VpgCr
#
#server:
#  port:
#    8082
#
#  application:
#    name: batch-api-back
#
#  cloud:
#    enable: false